/**
* This C Program generates the lexer that is required to be designed
* in response to the mid-sem exam question given to
* the CS F363 Compiler Construction class of
* Birla Institute of Technology and Science Pilani (BITS Pilani)
* K K Birla Goa Campus, GOA INDIA
* in Semester II, 2020-21.
*
* It takes as input the seed parameter, an ID number.
* The target language to be scanned is a set of ID numbers
* related structurally to this ID number, and
* that structural relation fits into a regexp.
* That means, it is a regular lagnuage.
*
* If the seed ID number is 201xA7PSklmnG, then
* the target language is generated by the regexp rA7stG where
* r=((200[4-9])|(201[0-{x}]))
* s=((PS)|(TS)|(A[1348A])|(B[1-5]))
* t=(([0-{k-1}][0-9][0-9][0-9])|(k(([0-{l-1}][0-9][0-9])|(l(([0-{m-1}][0-9])|(m[0-n]))))))
* For t above, if any of k, l, m, n is 0, then the [0-{?-1}] part is absent.
* Also if k is 0, then this regexp allows the serial number 0000 also, which is not a valid ID,
* but this is ignorable considering the rarity of the chance that this indeed will lead to
* lexical problems of accepting invalid strings and the complications are heavy to avoid it in the
* regexp itself. Instead, it should be checked in the action part.
*
* If the seed ID number is 201xyzA7klmnG, then
* the target language is generated by the regexp rsA7tG where
* r=((200[4-9])|(201[0-{x}]))
* s=((A[1348A])|(B[1-5]))
* t=(([0-{k-1}][0-9][0-9][0-9])|(k(([0-{l-1}][0-9][0-9])|(l(([0-{m-1}][0-9])|(m[0-n]))))))
* For t above, if any of k, l, m, n is 0, then the [0-{?-1}] part is absent.
* Also if k is 0, then this regexp allows the serial number 0000 also, which is not a valid ID,
* but this is ignorable considering the rarity of the chance that this indeed will lead to
* lexical problems of accepting invalid strings and the complications are heavy to avoid it in the
* regexp itself. Instead, it should be checked in the action part.
*
**/

#include<stdio.h>
#include<string.h>

int main(int argc, char *argv[]) {
	if(argc<2) {
		printf("Please supply your ID.\n");
		return -1;
	}
	if(strlen(argv[1])!=13) {
		printf("Are you sure you gave a valid ID?\n");
		return -2;
	}
	printf("%%option noyywrap\n");
	printf("\t#include<stdio.h>\n");
	printf("\t#include<string.h>\n");
	printf("\tint count1 = 0, count2 = 0, count3 = 0;\n\n");
	if(argv[1][4]=='A' && argv[1][5]=='7')
		printf("DUAL (A[1348A])|(B[1-5])|([PT]S)\n");
	else
		printf("DUAL (A[1348A])|(B[1-5])\n");
	if(argv[1][8]=='0')
		if(argv[1][9]=='0')
			if(argv[1][10]=='0')
				if(argv[1][11]=='0') {
					printf("Invalid SRNO 0000: %s\n",argv[1]);
					return -3;
				}
				else printf("SRNO 000[0-%c]\n",argv[1][11]);
			else printf("SRNO 00(([0-%c][0-9])|(%c[0-%c]))\n",argv[1][10]-1,argv[1][10],argv[1][11]);
		else printf("SRNO 0(([0-%c][0-9][0-9])|(%c(([0-%c][0-9])|(%c[0-%c]))))\n",argv[1][9]-1,argv[1][9],argv[1][10]-1,argv[1][10],argv[1][11]);
	else printf("SRNO ([0-%c][0-9][0-9][0-9])|(%c(([0-%c][0-9][0-9])|(%c(([0-%c][0-9])|(%c[0-%c])))))\n",argv[1][8]-1,argv[1][8],argv[1][9]-1,argv[1][9],argv[1][10]-1,argv[1][10],argv[1][11]);
	printf("%%%%\n");
	if(argv[1][4]=='A' && argv[1][5]=='7') {
		printf("200[4-9]A7{DUAL}{SRNO}G {\n");
		printf("											/* printf(\"ID %%s\\n\",yytext); */\n");
		printf("											count1++; count3++;\n");
		printf("											char s1[14];\n");
		printf("											strcpy(s1,yytext);\n");
		printf("											int x,y;\n");
		printf("											x= strncmp(s1,\"%s\",4);\n",argv[1]);
		printf("											y = strncmp(s1+8,\"%s\",4);\n",&(argv[1][8]));
		printf("											if(x<=0 && y<=0) count2++;\n");
		printf("										}\n");
		printf("201[0-%c]A7{DUAL}{SRNO}G {\n",argv[1][3]);
		printf("											/* printf(\"ID %%s\\n\",yytext); */\n");
		printf("											count1++; count3++;\n");
		printf("											char s1[14];\n");
		printf("											strcpy(s1,yytext);\n");
		printf("											strcpy(s1,yytext);\n");
		printf("											int x,y;\n");
		printf("											x= strncmp(s1,\"%s\",4);\n",argv[1]);
		printf("											y = strncmp(s1+8,\"%s\",4);\n",&(argv[1][8]));
		printf("											if(x<=0 && y<=0) count2++;\n");
		printf("										}\n");
		printf("20......[0-9][0-9][0-9][0-9]G { /* Other IDs: */ count3++; }\n");
		printf(". { /* Anything else: Ignore */ }\n");
	}
	else {
		printf("200[4-9]{DUAL}A7{SRNO}G {\n");
		printf("											/* printf(\"ID %%s\\n\",yytext); */\n");
		printf("											count1++; count3++;\n");
		printf("											char s1[14];\n");
		printf("											strcpy(s1,yytext);\n");
		printf("											s1[4] = '\\0'; s1[12] = '\\0';\n");
		printf("											int x = strcmp(s1,\"2009\"), y = strcmp(s1+8,\"0463\")\n");
		printf("											if(x<=0 && y<=0) count2++;\n");
		printf("											printf(\"%s\n\",yytext);\n");
		printf("										}\n");
		printf("201[0-%c]{DUAL}A7{SRNO}G {\n",argv[1][3]);
		printf("											/* printf(\"ID %%s\\n\",yytext); */\n");
		printf("											count1++; count3++;\n");
		printf("											char s1[14];\n");
		printf("											strcpy(s1,yytext);\n");
		printf("											s1[4] = '\\0'; s1[12] = '\\0';\n");
		printf("											int x,y;\n");
		printf("											x = strcmp(s1,\"2019\");\n");
		printf("											y = strcmp(s1+8,\"0463\");\n");
		printf("											if(x<=0 && y<=0) count2++;\n");
		printf("											printf(\"%s\n\",yytext);\n");
		printf("										}\n");
		printf("20......[0-9][0-9][0-9][0-9]G { /* Other IDs: */ count3++; }\n");
		printf(". { /* Anything else: Ignore */ }\n");
	}
	printf("%%%%\n\n");
	printf("int main(void) {\n\tyylex();\n\tprintf(\"%%d %%d %%d\\n\",count1, count2, count3);\n}\n");
	return 0;
}
